#!/usr/bin/env ruby

require 'vantiv'
require 'vantiv/certification/validation_test_runner'

unless ENV['ACCEPTOR_ID'] && ENV['LICENSE_ID'] && ENV['PAYPAGE_ID']
  raise "Vantiv License ID, Acceptor ID, Paypage ID and Application ID required"
end

Vantiv.configure do |config|
  config.license_id = ENV["LICENSE_ID"]
  config.acceptor_id = ENV["ACCEPTOR_ID"]
  config.paypage_id = ENV["PAYPAGE_ID"]

  config.default_report_group = '1'
end

Vantiv::Certification::ValidationTestRunner.run(
  filter_by: ENV["FILTER_BY"],
  save_to: "certs.txt"
)

%x(open certs.txt)
